### ISSUE TITLE
Symbol support with symbol overrides

### ISSUE THREAD

**Issue by custa1200** [contentsync/SketchContentSync.sketchplugin#10]
Currently there appears to be no way to deal with pulling content from the spreadsheet using the symbol overrides.

**Comment by dbrody** [comment]
Hi @custa1200 , Did you see the version 0.3.1? That has new symbol support. Is that what you are looking for?

**Comment by dbrody** [comment]
@custa1200, were you able to look at the new symbol support? Would love your opinion on it.

This issue will be closed at the end of the week unless there are additional comments here.

**Comment by custa1200** [comment]
Hey @dbrody I'll check it out agin soon but I am pretty sure that I was unable to get it to work with nested symbols last time I tried. I'll put together a small file later today to test it out how I would be using it.

**Comment by dbrody** [comment]
That would be great. I don't think it currently supports nested symbols, so seeing an example of how you may use it would be helpful.

**Comment by dbrody** [comment]
Since this issue is on symbol overwrites which are supported now, we are closing this issue.

This topic can be continued for Supported Nested Symbols in issue #12
