### ISSUE TITLE
Copy/Paste issues

### ISSUE THREAD

**Issue by StijnEversdijk** [contentsync/SketchContentSync.sketchplugin#11]
As soon as I run the plugin on a slightly more complex Sketch-file, I have no longer the ability to copy/paste within the document. Duplicate (CMD+D) does work, but CMD+C/V/X doesn't do anything or has the app crashing.

Running the latest version of Sketch; 40.3

**Comment by dbrody** [comment]
@StijnEversdijk Are you still experiencing this issue? Have you tried the newest release of SketchContentSync and Sketch 41.2?

**Comment by StijnEversdijk** [comment]
@dbrody Wanted to check whether the issue was still relevant. With the new app and website it took me way longer to get up and running again and the UX was extremely confusing. Since I didn't want to give my credit card details to check if an app is still malfunctioning I am afraid I don't know :(

**Comment by dbrody** [comment]
@StijnEversdijk As a side note, credit cards are no longer required to try the application. You can use the full version for 30 days for free without a credit card now.

**Comment by dbrody** [comment]
@StijnEversdijk Without any update here and no other comments from others, we are considering this closed for now given the update to V1.1.1.

If you do experience any problems regarding this, feel free to create a new Open Issue.
