### ISSUE TITLE
Symbol content sync broken in Sketch 41?

### ISSUE THREAD

**Issue by Joshuwar** [contentsync/SketchContentSync.sketchplugin#13]
Looks like the symbols API changed week ago when Sketch released version 41. 

Symptoms: after updating Sketch, contentSync neither imports content into 'sync fields' within symbol instances, nor overrides content in symbols where it should. Normal (non-symbol) text fields update as expected.

Hopefully it's not a big fix. Let me know if you're not getting this behaviour with Sketch 41; it's possible I've made a mistake somewhere.

**Comment by dbrody** [comment]
Yes, this was from an update to the Sketch API. It is now fixed with the latest release:

https://github.com/contentsync/SketchContentSync.sketchplugin/releases/tag/v0.3.3

Let me know here if that fixes your problem and we can close the issue. Thank you for the notice!

**Comment by Joshuwar** [comment]
Hey, nice one. Just had a chance to try your update and it's working for symbols (including custom overrides) in Sketch 41.2. Thanks for your continued attention on this- it's shaping up to be really useful.
