### ISSUE TITLE
The plugin generate a error with symbol

### ISSUE THREAD

**Issue by VictorienDotNet** [contentsync/SketchContentSync.sketchplugin#16]
Hello,
I observed a bug when I use symbol. The plugin don't synchronise the text and generate a error. :)

P.S : Your plugin is very nice and useful.

`27/11/16 19:46:02,329 Sketch[627]: Exception: TypeError: _layer.applyOverrides is not a function. (In '_layer.applyOverrides(mutableValues)', '_layer.applyOverrides' is undefined)
27/11/16 19:46:02,329 Google Sync (Sketch Plugin)[627]: TypeError: _layer.applyOverrides is not a function. (In '_layer.applyOverrides(mutableValues)', '_layer.applyOverrides' is undefined)
line: 126
sourceURL: /Users/victorien/Library/Application Support/com.bohemiancoding.sketch3/Plugins/SketchContentSync.sketchplugin/Contents/Sketch/sync.google.cocoascript
column: 26
stack: sync@/Users/victorien/Library/Application Support/com.bohemiancoding.sketch3/Plugins/SketchContentSync.sketchplugin/Contents/Sketch/sync.google.cocoascript:126:26
updateTextBoxes@/Users/victorien/Library/Application Support/com.bohemiancoding.sketch3/Plugins/SketchContentSync.sketchplugin/Contents/Sketch/sync.google.cocoascript:250:25
onRun@/Users/victorien/Library/Application Support/com.bohemiancoding.sketch3/Plugins/SketchContentSync.sketchplugin/Contents/Sketch/sync.google.cocoascript:219:24`

![screen shot 2016-11-27 at 19 49 02](https://cloud.githubusercontent.com/assets/5654077/20650945/343fc986-b4db-11e6-852c-144c1b822782.png)

![screen shot 2016-11-27 at 19 54 23](https://cloud.githubusercontent.com/assets/5654077/20650950/507ec1ec-b4db-11e6-98dd-4b65b64c4f36.png)

**Comment by dbrody** [comment]
Yes, this has now been fixed with the most recent release:

https://github.com/contentsync/SketchContentSync.sketchplugin/releases/tag/v0.3.3
