### ISSUE TITLE
Generate keys in spreadsheet from .sketch file

### ISSUE THREAD

**Issue by kimmybolke** [contentsync/SketchContentSync.sketchplugin#21]
Hi,

Great project! I've got a feature request. It would be great if all the keys in the spreadsheet could be generated from the layers named "sync:" in a sketch file. 

In my case I've made loads of screens in Swedish and would like to just generate a spreadsheet with all the keys and the Swedish version in one column. Then translate everything to English in another column, and sync to see that the design doesn't break. 

Thanks,
Kimmy

**Comment by dbrody** [comment]
Hi Kimmy,

Yes, great suggestion. We are working to add that feature in the next release - we agree that would be hugely helpful and have seen a few others request a similar features.

Thanks!
David

**Comment by dbrody** [comment]
@kimmybolke 

We have released V1.1.1 which includes the ability to Push content. This requires updating the OSX App to version 0.7.1 too. This new update will allow you to push all text layers in your sketch file into the google document.

**Comment by dbrody** [comment]
Since the updates in V1.1.1 and OSX ContentSync.app version 0.7.1 includes this feature we are closing this issue.

We hope you enjoy the new features and file any ideas / issues which could make it better.
