### ISSUE TITLE
Extremely slow

### ISSUE THREAD

**Issue by billbetocl** [contentsync/SketchContentSync.sketchplugin#23]
Anyway to speed up the sync? Also crashes if you go between Windows. Not stable when multitasking.

**Comment by dbrody** [comment]
Hi @billbetocl , yes, in version 0.6.16 of the OSX App we have implemented a couple of updates to both our API and how we use the Google API which should drastically help the performance. We are still looking into more options to continue improving the speed.

In terms of the "Also crashes if you go between Windows. Not stable when multitasking.", can you give more details on how and what you are experiencing?

**Comment by dbrody** [comment]
@billbetocl Any followup as to your concerns over the "Not stable when multitasking."? We'd love to make sure our application does not interfere with your workflow. Any details would help tremendously.

**Comment by dbrody** [comment]
I'm closing this issue as it is inactive and not update as of 0.6.16.
