### ISSUE TITLE
Content Keys non detected

### ISSUE THREAD

**Issue by NievesG** [contentsync/SketchContentSync.sketchplugin#24]
I have a problem with the plugin, I have a Google sheet with 765 rows, when I try to refresh the linked content in my web panel in contentsync.io does not detect the content keys. I've tried all possible formats and I think it's a problem with the number of rows the script can read. Could you tell me please how I can solve this problem?

**Comment by dbrody** [comment]
Hi @NievesG , yes, we recently fixed an issue with blank rows in a spreadsheet causing issues where the content on the web application would not load. It looks like that issue was solved right after you posted this comment. It could be that your document had a blank row. Also, yes, 765 rows is quite the size. We are still looking into ways to improve the performance on larger requests. Can you try again and see if the issue still occurs with updates since?

**Comment by dbrody** [comment]
@NievesG Looks like another issue is if there is a duplicate key on your google doc. The web platform currently has an error with that. We are looking into a fix now.

**Comment by NievesG** [comment]
Ok thank you @dbrody, I'll wait until you solve it. 

On the other hand, I have created many test projects to try to understand where the problem was. But now I would like to eliminate them and I do not know how do it. 

Regarding the blank rows, I have many because I'm waiting some translation. But I don't know why It doesn't work because I have used your plugin in October and It worked great!

Finally, I would like to know how many rows there are for each project.

Thank you very much

**Comment by dbrody** [comment]
@NievesG, the content keys should now be fixed and show up in the content pane. It will also now show you if it detects a blank line / a duplicated key.

Agreed. The addition of the private documents and using the Google API and our platform has made the application a bit more complicated.  But we believe the possibilities of the added complexity behind the scenes of this platform are worth it when we look down the road. We have some bigger updates coming end of this week with supporting deleting projects, sharing projects, creating organizations and more. Furthermore, on the horizon we see some exciting possibilities such as syncing formatting per version, automated translations, and more.

Thank you for all your feedback so far :)

**Comment by dbrody** [comment]
@NievesG This should be fixes as we have no seen any more reports of this issue. I will consider this item closed.
