### ISSUE TITLE
Text Without Key Changing In Sketch File

### ISSUE THREAD

**Issue by nmarketti** [contentsync/SketchContentSync.sketchplugin#28]
I'm having an issue where text layers without the **sync:** designation are still changing. They are items I didn't set up in a excel doc but somehow are still changing.

**Comment by dbrody** [comment]
@nmarketti 

A few follow up questions just to clarify to help target the fix:

- This is during a pull?
- What are they changing to?
- Just to confirm, there is no key in the google document that matches the layer name?

Thanks,
David

**Comment by nmarketti** [comment]
@dbrody 

Sure!

1. Yes this was during a pull.
2. They are changing to keys in the document. But they are not related.
3. Correct. There is no key that matches the layer name. 

I've attached references and highlighted to show the Sketch doc layer names, the changed content and the keys it's changing too.

Also -- I realized as well that when I CMD+Undo the sync. And try to SYNC again...it will change to something completely different than the first Sync. 

My work around was to just delete and re-add with different layer names for the time being.
![sync-key-exampletwo](https://cloud.githubusercontent.com/assets/6658253/23776954/0df00f86-04f7-11e7-8526-ee1e569ef5fb.png)
![sync-key-example-one](https://cloud.githubusercontent.com/assets/6658253/23776956/0df37df6-04f7-11e7-9e24-37ba693e08c2.png)
![sketch](https://cloud.githubusercontent.com/assets/6658253/23776955/0df07282-04f7-11e7-9dbb-98d65136b3e3.png)

**Comment by dbrody** [comment]
@nmarketti 

I've set up an example to try to reproduce it:

- A Sketch file with text layers named 'test1', 'test2', 'test3'
- A google spreadsheet with only keys 'test1', 'test2'
- I pulled down the partial version

I'm seeing that the text layer 'test3' stays unchanged on my setup so I can't seem to easily reproduce the issue.

Could you elaborate on what the key names were which were being replaced when they shouldn't have been? If you have any specifics on how to replicate it that would be a huge step in being able to submit a fix for it.

Thanks!

**Comment by nmarketti** [comment]
@dbrody 

I just set up a document to reproduce it and it worked.

- A sketch file with four layers named 'HR', 'sync:testHr', '*', and 'test'
- A google spreadsheet with a key 'testHr' and a value of 'NAVIGATION'
- Did a pull, and it changed all text layers to 'NAVIGATION'

I did an additional test as well:

- Added a new layer and named it 'David' with no **'sync:'** in the layer name
- Added a key in the spreadsheet with the Key name being 'David', and value 'Brody'
- Did a pull, and it pulled the key value from the spreadsheet, **without the 'sync:'** abbreviation on the text layer.

This should be more clear. Let me know if it works for you.

Thanks!

**Comment by dbrody** [comment]
@nmarketti 

Ah, yes!

So this is a *feature* in version 1.1.1.

The concept here is for better support of pushes and initial setups on new projects. By being agnostic of the `sync:` it prevents a user or ContentSync from having to rename layers which can be a lot of manual work and also may interfere with other plugins.

The use case to prevent that behavior would be one of two ways:

- Remove the spreadsheet key ('David' in your example) to prevent it from syncing the value
- Remove the key during the Push prompt where you can use the X to not push specific keys:

![screen-shot-2017-03-10-at-9 48 26-am](https://cloud.githubusercontent.com/assets/210322/23806583/12a28736-0577-11e7-92d2-81ec003ad9ee.png)


Hope that answers your question about this behavior. We are working on an update of the README to make that a bit more clear.

For your use cases, is this acceptable behavior?

**Comment by nmarketti** [comment]
Interesting...

The removal of the Sync is great! However, I do rename all my layers as I design and build it in the spreadsheet simultaneously. Since I'm using this as the client manages copy, I am specific about key names that correlate with each section.

I think the main issue I'm concerned about moving forward is that if I have this situation:

- A layer named headerDavid and a key that is headerDavid with a value of 'My name is David Brody'
- Another layer somewhere just called David.

When you have that scenario, even though the word 'header' is not before the name David, it will still change **both** layer names on my Sketch document.

This is probably something that would happen not often, but it's still something where I would have to find and fix when working on large scale projects, which I'm currently using this for.

**Comment by dbrody** [comment]
Ah, yes. That is an issue. Thanks for working with me here to identify it. I can reproduce that and yes, that should not be happening.

We will get that fixed soon.

**Comment by nmarketti** [comment]
Of course! Thanks for working on this platform. 

It's a game changer for managing website content and the speeding up of workflow. 

💯 

Cheers!

**Comment by dbrody** [comment]
@nmarketti 

Version 1.1.2 should now fix this issue. You can go into settings on the app and click uninstall and the install to update the version.

![screen shot 2017-03-10 at 11 12 51 am](https://cloud.githubusercontent.com/assets/210322/23809425/86afc0b6-0582-11e7-9b29-fe6db3f8a447.png)

Glad you find it useful! As always, don't hesitate to file more issues, comments, ideas, etc.  Thank you for being a user!

If you can, please reply here just to confirm it is fixed for you too after updating. After that, we can consider this issue closed 👍

**Comment by nmarketti** [comment]
Confirmed fix. 

Done deal my friend. Thanks! 🎉

**Comment by dbrody** [comment]
Great! Thank you for using ContentSync!
