### ISSUE TITLE
Duplicate layer names are all treated as the same content

### ISSUE THREAD

**Issue by contentsync** [contentsync/SketchContentSync.sketchplugin#30]
# Issue
If there are many layers throughout a design that have the same name, they will all be treated as the same content. This is an issue when pushing / pulling as it will overwrite some of the content with data from other locations in the sketch.

# Potential Solutions

## More Context To A Key
One proposed solution is to use context to expand on a text field's name. So if I have a text layer named "Text" on an artboard name "Artboard" instead of the current key `Text` it would be something such as `Page.Artbord.Text`. If the layer is then within a Layer Group for example it would be: `Page.Artboard.Layer Group.Text`.

## Use ObjectIDs
Each object in Sketch does have a unique key. This could be added as an additional metadata column in the Google Spreadsheet either as an additional Column A.

## Etc
Other potential solutions...

**Comment by dbrody** [comment]
As of ContentSync 0.8.2 and Sketch ContentSync 2.4.1 there are now settings options in the project settings panel. The option, **Include Layer Context Details** will now make additional context per each layer:

![screen shot 2017-04-19 at 4 40 44 pm](https://cloud.githubusercontent.com/assets/210322/25206847/6121562c-251f-11e7-99e2-24fd356a284a.png)

With this option on, it will create two additional columns in the Google Spreadsheet:

**Column A** will be Object ID. This is a unique ID per sketch layer.

**Column B** will be Path. This is a unique path to the layer from the page, through groups and symbols to the text layer. An example would be: _Page 1.Group A.Text Layer_.
