### ISSUE TITLE
Uploads with styles break when font sizes have decimals

### ISSUE THREAD

**Issue by dbrody** [contentsync/SketchContentSync.sketchplugin#32]
Pushes seem to not work if text has a decimal point, for example a font size of 11.5.

**Comment by k0mrad** [comment]
i'm having issues with this. All my text styles disappear as soon as content is synced.

**Comment by dbrody** [comment]
@k0mrad 

Interesting. A couple Questions:
+ Are you pulling or pushing content?
+ Does your google document have styles in it?
+ Do you have the Sync Content Styles setting turned on? (see below)

# Sync Content Styles
There are two ways to use this:

## You Want Styles Synced
**This requires the google document's content to have the styles you want.**
This will copy the styles of the google document into your sketch file. Careful as if the styles aren't in the google document then it will be overwritten.
To use this you need to turn on syncing styles in the project settings:
![screen shot 2017-03-31 at 10 11 38 am](https://cloud.githubusercontent.com/assets/210322/24561125/7bedf372-15fa-11e7-9f80-7e452f7bb3bc.png)

## You want only the text content to sync
In this case, you only want to the content to sync. This will overwrite any layers that have styles on the text (i.e. a single word in a sentence is bolded). For this, you turn off the Sync Content Styles.
![screen shot 2017-03-31 at 10 13 14 am](https://cloud.githubusercontent.com/assets/210322/24561186/ad713314-15fa-11e7-8c68-b35e45589b10.png)

**Comment by k0mrad** [comment]
totally my miss @dbrody I am coming from the original plugin and didn't notice this amazing new feature

**Comment by dbrody** [comment]
Let us know what you think!

**Comment by dbrody** [comment]
Also, make sure you are on the latest Sketch Content Sync (2.3.0) and ContentSync.app (0.7.7) versions.

**Comment by k0mrad** [comment]
both installed, This is very useful.  is it possible to push all the content and then change the key titles within a spreadsheet or do I need to do this first in the sketch file?

**Comment by dbrody** [comment]
@k0mrad Can you clarify a bit more? Not sure I completely understand. Also, could you submit it as a new issue? So others can find it easily for reference.

**Comment by dbrody** [comment]
Closing this issue as it now does not break pushing / pulling. Instead, ContentSync / Google Spreadsheets will round the font size to the nearest decimal.
