### ISSUE TITLE
Ignore text layers on Push

### ISSUE THREAD

**Issue by ednerd** [contentsync/SketchContentSync.sketchplugin#34]
Hey @dbrody 

Now that there is no need to add the "sync:" prefix to text layers I want to sync, I find when I do an initial Push on a new project I have many text layers that I don't need to sync (e.g. device keyboards, font icons, text design elements... etc.) I could "X" every text layer I don't want to push but, I'd have to do that again on any subsequent Push. So, either I need a way to tag text layers that I don't want to sync at all in my sketch file OR after the initial Push where I deselect each text layer I don't want to push, that somehow persists on subsequent Pushes. (I think I just confused myself)

Thanks

**Comment by dbrody** [comment]
@ednerd 

# V2.3.0 Released
Just release v2.3.0 with a new inspector view.

This view allows for enabling/disabling ContentSync per layer (or group of selected layers). This will persist on a single computer across syncs and Sketch usages (however the settings are not yet synced to the cloud so the settings are only per user).

### First, turn on ContentSync Shortcuts
Go to project settings and turn on the ContentSync Shortcuts (or CMD + = in Sketch):
![screen shot 2017-03-30 at 9 10 33 am](https://cloud.githubusercontent.com/assets/210322/24514336/c7408452-1528-11e7-89db-57f01d971f26.png)


### ContentSync Inspector
Now when you select a layer (or group of layers) you will see an additional element in the Inspector panel which you can use to enable/disable ContentSyncing for the selected layers:

#### Selected Layers Are Disabled:
![screen shot 2017-03-30 at 9 11 44 am](https://cloud.githubusercontent.com/assets/210322/24514374/ef7698da-1528-11e7-9908-0e2fde6c36dd.png)

#### Selected Layers are Enabled:
![screen shot 2017-03-29 at 11 59 10 pm](https://cloud.githubusercontent.com/assets/210322/24514428/183b1746-1529-11e7-95b0-0d3ea369e47f.png)

#### Selected Layers are a mixture of enabled and disabled:
![screen shot 2017-03-29 at 11 59 30 pm](https://cloud.githubusercontent.com/assets/210322/24514435/1fd7db4c-1529-11e7-85e1-301c88488ac7.png)

Hope this helps!

**Comment by ednerd** [comment]
Great! That should help.
