### ISSUE TITLE
Sketch Content Sync keyboard shortcut

### ISSUE THREAD

**Issue by msawmiller** [contentsync/SketchContentSync.sketchplugin#42]
I noticed the shortcut to toggle this plugin is ⌘=. That's the default key in sketch to zoom in. Can you guys change it or give me guidance how I can overwrite it? Keyboard shortcuts in accessibility seem to no do the trick.

Thanks!

**Comment by dbrody** [comment]
@msawmiller, thanks for the note. Yes, our shortcuz is ⌘= while zoom in is ⌘+. However it seems many people do use ⌘= for zoom as well. We will look for an alternative.

**Comment by msawmiller** [comment]
There must be a bug. For me, ⌘+ actually toggles sketch content sync and ⌘= zooms in. Since installing the plugin, my normal functionality somehow changed.

**Comment by dbrody** [comment]
Interesting. We do not see that. Can you confirm:

- Which sort of keyboard are you on
- `⌘ + Shift + '='` should be Zoom In
- `⌘ + '='` should be ContentSync

If that is not the case, then we will investigate further.

**Comment by msawmiller** [comment]
Apple bluetooth keyboard. http://sketchshortcuts.com/
I think I know what the issue is. By default sketch honors ⌘+  or ⌘ Shift +.

Yea maybe different keyboard shortcut can get around this.

**Comment by dbrody** [comment]
@msawmiller This is now updates as of 2.4.3.
