### ISSUE TITLE
App Shortcut in Sketch

### ISSUE THREAD

**Issue by nmarketti** [contentsync/SketchContentSync.sketchplugin#49]
With the "Enable Shortcuts" on, pulling from within Sketch opens the ContentSync app, but I still have to click what "version" to pull after I click a version within the SketchApp box.

Is it intended to automatically pull the version you select?

If not, have you considered having it automatically pull?

**Comment by dbrody** [comment]
@nmarketti Currently it is just a shortcut to the action in the ContentSync.app.

We have considered it and its a great idea. Based on priorities, it will probably make it into the next major version update down the road.

However, priorities will also be based on reactions and 👍  on issues so it could be sooner.

**Comment by dbrody** [comment]
@nmarketti This is a great idea. We decided to prioritize this to help with the usability and sign up flow. We hope you enjoy the 3.0.0 updates!

Sketch ContentSync 3.0.0 now makes ContentSync much more integrated directly within Sketch. Now you can log in, set projects, change settings and push/pull directly within Sketch. ContentSync.app is not used/required anymore.

We hope this greatly simplifies the process and addresses this ticket.

Let us know what you think!

Thanks,
David
