### ISSUE TITLE
Pulling not starting a Pull

### ISSUE THREAD

**Issue by nmarketti** [contentsync/SketchContentSync.sketchplugin#50]
When clicking "Pull Content", button goes dark green into active click state, but then after a few seconds returns to normal state and does nothing.

I tried creating a new project and adding a excel doc from there...still no luck. Only seems to happen on this one Sketch file I have. All others are working properly.

Thoughts?

**Comment by dbrody** [comment]
@nmarketti Interesting. Can you provide some details?

- Name of Sketch file?
- Is the sketch file saved?

This is strange: You say all others are working? I'm not seeing any pull logs recently. When was the last time you tried pulling?

**Comment by dbrody** [comment]
This issue has been closed as of 2.4.4.

The issue was image overrides on symbol instances caused issues with the JSON transport. That has been fixed as of 2.4.4.
