### ISSUE TITLE
Support Sketch 45 plugin update system

### ISSUE THREAD

**Issue by bomberstudios** [contentsync/SketchContentSync.sketchplugin#53]
Hi there!

This is a quick note to remind you that Sketch 45 will include a plugin update system.

It would be awesome if you could add support to it (it's really easy!) before Sketch 45 comes out. Ideally, you should release an update for your plugin while we're still in Sketch 44, so your users will have a nice & easy experience when 45 is released.

For more details, please check http://sketchplugins.com/d/229-updating-plugins and http://developer.sketchapp.com/introduction/updating-plugins/

Thanks in advance!

**Comment by dbrody** [comment]
@bomberstudios 

We just launched https://www.appcastify.com to help people with AppCast files. It also is a great way to get statistics and easily maintain the file.

Its a very early product, but would love your thoughts!

We'll be using this to add better AppCast support into our products.

**Comment by dbrody** [comment]
Thanks for letting us know about this coming update. SketchContentSync now includes an appcast as of hash c512fd2859b81a7395c602b49266434891bd558f.

**Comment by bomberstudios** [comment]
🙌
