### ISSUE TITLE
Issue with sync document in account Google enterprise

### ISSUE THREAD

**Issue by quiqueciria** [contentsync/SketchContentSync.sketchplugin#6]
Hi, I have a enterprise account in Google and this don't permit publish google document if you aren't logged with the account of enterprise before. Yes it permit publish the docuement like other one, but only view  for account of the enterprise.
Is there some way for do the sync if isn't the document  public for everyone? 

Thank in advance!

**Comment by dbrody** [comment]
Hi @quiqueciria , yes, it is a challenge that needs to be looked in to. For now, try to use https://sheetsu.com/ to help get around this. You should be able to use that URL in the plugin as well. If you have trouble, I can follow up with a more detailed response.

**Comment by dbrody** [comment]
@quiqueciria  Just wanted to let you know we have launched the ContentSync Platform which allows you to now synchronize your content into google enterprise. This allows using private google documents.

Check it out more at [contentsync.io](contentsync.io)

**Comment by quiqueciria** [comment]
@dbrody thanks! sound good. I have seen that is necessary a credit card for to use a private sheet. I will say it to my boss 😁

**Comment by dbrody** [comment]
@quiqueciria with ContentSync platform available, I hope it solves the need to access private docs. We are continuing the make the platform better and add new features. So stay tuned. If you have any more comments, issues, questions, etc, either post another issue here or send a not to support@contentsync.io . Thank you again for the note, and for using ContentSync!
