### ISSUE TITLE
Support for private sheets

### ISSUE THREAD

**Issue by dbrody** [contentsync/SketchContentSync.sketchplugin#9]
There have been a couple of people asking for access to private sheets without the need to publish the sheet to web. While sheetsu does help, there may be alternatives that work better for other use cases.

If anybody has desire for such feature, could you please comment a bit about your use case and what your ideal solution would be?

Initial thoughts are to use Google OAuth.

**Comment by gonsalves** [comment]
Ideally, there shouldn't be a major workflow change, as (at least amongst my clients), Google Docs is perhaps the most technical tool a lot of the content editors are able to use. For content editors/translators, their existing workflows shouldn't change.

**Comment by karincurkowicz** [comment]
I have a use case. I always work for companies that have strict internal data privacy policies. e.g. nothing goes outside the approved firewall. This is particularly true when we're talking about new product development.  Putting design data to "google's" servers would be a serious no-no. 

The ideal solution would be to put a spreadsheet of any file type (excel, or sheets) on a secure git repo or internal server, and direct the plugin to the appropriate path. 

Imagine how management would react if they discovered designers at Amazon were putting design content in a spreadsheet on a server at Google to enable this plug-in? What if they were designers at Apple or Palantir? - All bad for the designer.

**Comment by k0mrad** [comment]
@karincurkowicz running the sheet through sheetsu.com makes it accessible to the sync plugin. Worked great for me.

**Comment by dbrody** [comment]
@karincurkowicz Does sheetsu.com work for you? We've had good luck with it but would love to hear any builds on how this could appeal to internal groups at a Palantir or Apple sort of security level company.

**Comment by drkanukie** [comment]
Same here public sheets are a no no as they can leak IP.  

Sheetsu also a no no as third party hosted service. So no good for security conscious third party companies. It has to be on your corp network or corp local machine.

It would be great if you could sync to a authenticated JSON endpoint on a URL or a local JSON file - that way a server could be hosted by anyone on their corp network and you would be able to push the JSON file from whatever tools you have internally.

Requirements are the access to the data file needs to be on your network and the plugin needs to support web authentication or local files.

**Comment by dbrody** [comment]
@drkanukie @karincurkowicz @gonsalves 

Hi all, we are making a ContentSync Platform version, which will allow for similar functionality to google sheets but a bit more specialized control for these purposes. It allows for various permissions on each 'version' and will provide authenticated access via Sketch. Does this sound like something useful?

**Comment by drkanukie** [comment]
You need something that works with privately shared sheets. How would your
proposal work? We use shared sheets a lot but need confidential access for
sensitive projects

**Comment by dannypaton** [comment]
@dbrody 
ContentSync Platform version sounds amazing!! 
When do you think this will be available to download?

**Comment by dbrody** [comment]
It should be available by end of next week.

**Comment by dbrody** [comment]
@dannypaton @drkanukie @karincurkowicz @k0mrad @gonsalves 

Hi all. We are very excited to announce a milestone release for ContentSync.

Check it out at [https://contentsync.io/](https://contentsync.io)!

I'm looking forward to hearing any and all feedback.

Enjoy!

**Comment by drkanukie** [comment]
Private connection I'm excited. Will try when I get into work today.

**Comment by dbrody** [comment]
Hey everybody we are very excited to have ContentSync Platform live and usable for the last few weeks. We are constantly continuing to enhance and add to it. If you have any comments, issues, requests, etc, please post them in a new issue or send an email to support@contentsync.io . Happy using!
